version: '3.9'

volumes:
   geoserver-data:

services:
   geoserver:
      image: pascallike/geoserver:2.20.6.LOGS
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
      environment:
        - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
        - GEOSERVER_ADMIN_PASSWORD=geoserver
        - GEOSERVER_ADMIN_USER=admin
        - INITIAL_MEMORY=1G
        - MAXIMUM_MEMORY=2G
        - COMMUNITY_EXTENSIONS=sec-oauth2-openid-connect-plugin
      ports:
       - "8080:8080"
